-- +goose Up
CREATE TABLE users (
  id UUID PRIMARY KEY NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  username VARCHAR(21) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

-- +goose Down
DROP TABLE users;