// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const userFeedsAfter = `-- name: UserFeedsAfter :many
SELECT
  p.id,
  p.author_id,
  p.title,
  p.content,
  p.created_at,
  p.updated_at
FROM posts p
WHERE p.author_id IN (
  SELECT f.followee_id
  FROM follows f
  WHERE f.follower_id = $1::uuid

  UNION

  SELECT $1::uuid
)
AND (
  p.created_at,
  p.id
) < (
  $2::timestamptz,
  $3::uuid
)
ORDER BY p.created_at DESC, p.id DESC
LIMIT $4
`

type UserFeedsAfterParams struct {
	UserID          uuid.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
	PaginationLimit int32
}

func (q *Queries) UserFeedsAfter(ctx context.Context, arg UserFeedsAfterParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, userFeedsAfter,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PaginationLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userFeedsFirst = `-- name: UserFeedsFirst :many
SELECT
  p.id,
  p.author_id,
  p.title,
  p.content,
  p.created_at,
  p.updated_at
FROM posts p
WHERE p.author_id IN (
  SELECT f.followee_id
  FROM follows f
  WHERE f.follower_id = $1::uuid

  UNION

  SELECT $1::uuid
)
ORDER BY p.created_at DESC, p.id DESC
LIMIT $2
`

type UserFeedsFirstParams struct {
	UserID          uuid.UUID
	PaginationLimit int32
}

func (q *Queries) UserFeedsFirst(ctx context.Context, arg UserFeedsFirstParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, userFeedsFirst, arg.UserID, arg.PaginationLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
