// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (
  followee_id, follower_id
) VALUES (
  $1, $2
)
`

type FollowUserParams struct {
	FolloweeID uuid.UUID
	FollowerID uuid.UUID
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FolloweeID, arg.FollowerID)
	return err
}

const followersCount = `-- name: FollowersCount :one
SELECT
  COUNT(*)
FROM follows
WHERE followee_id = $1
`

func (q *Queries) FollowersCount(ctx context.Context, followeeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, followersCount, followeeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE
FROM follows
WHERE
  followee_id = $1 AND follower_id = $2
`

type UnfollowUserParams struct {
	FolloweeID uuid.UUID
	FollowerID uuid.UUID
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FolloweeID, arg.FollowerID)
	return err
}
