// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (
  id, user_id, title, content, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
`

type CreatePostParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE 
FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const findPostByID = `-- name: FindPostByID :one
SELECT
  id, user_id, title, content, created_at, updated_at
FROM posts
WHERE
  id = $1
`

func (q *Queries) FindPostByID(ctx context.Context, postID uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, findPostByID, postID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPostsAfter = `-- name: ListPostsAfter :many
SELECT
  id, user_id, title, content, created_at, updated_at
FROM posts
WHERE
  (created_at, id) < (
    $1::timestamptz,
    $2::uuid
  )
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListPostsAfterParams struct {
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
	PaginationLimit int32
}

func (q *Queries) ListPostsAfter(ctx context.Context, arg ListPostsAfterParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsAfter, arg.CursorCreatedAt, arg.CursorID, arg.PaginationLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsFirst = `-- name: ListPostsFirst :many
SELECT
  id, user_id, title, content, created_at, updated_at
FROM posts
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListPostsFirst(ctx context.Context, paginationLimit int32) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsFirst, paginationLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET
  title = $2,
  content = $3,
  updated_at = NOW()
WHERE id = $1
`

type UpdatePostParams struct {
	ID      uuid.UUID
	Title   string
	Content string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.Exec(ctx, updatePost, arg.ID, arg.Title, arg.Content)
	return err
}
